server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://casino-backend:3000/api/auth/;
    }

    location /api/usuarios/ {
        proxy_pass http://casino-backend:3000/api/usuarios/;
    }

    location /api/juegos/ {
        proxy_pass http://casino-backend:3000/api/juegos/;
    }

    location /api/transacciones/ {
        proxy_pass http://casino-backend:3000/api/transacciones/;
    }

    location /api/bonos/ {
        proxy_pass http://bonos-service:8004/api/bonos/;
    }

    location /api/apuestas/ {
        proxy_pass http://apuestas-service:8002/api/apuestas/;
    }

    location /api/estadisticas/ {
        proxy_pass http://estadisticas-service:8005/api/estadisticas/;
    }

    location ~* \.(?:js|css|woff2?|svg|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}